# 错误处理
---

## 不可恢复错误

rust中的错误抛出机制：

```rust
// panic抛出错误, 用于不可恢复错误处理
panic!("xx");  // panic会使程序终止
```

## 可恢复错误

### Option类型

Option<T>枚举用于存在和不存在情况处理。

```rust
// Option<T>枚举类型
fn match_option(val: Option<&str>) {  // 使用match模式处理
    match val {
        Some("xx") => println!("xx"),  // 找到属于T类型的元素
        None => println!("no"),  // 找不到相应元素
}}

// 使用 ? 解开Option
fn last_char(text: &str) -> Option<char> {
    text.lines.next()?.chars().last()
}  // next()返回Option类型, 若是Some(&str)继续处理, 所示None直接返回None
// ?后必须有一个变量承载其值, 如只能是let x = arr.get(0)?; 而不是: arr.get(0)?

// 使用unwrap处理Option
fn unwrap_option(val: Option<&str>) {
    let result = val.unwrap();  // unwrap接收到None时将返回panic
    if result == "other" { panic!("xx"); }  // 其它场景处理
}
```

### Result类型

Result<T, E>类型用于可恢复错误场景。

```rust
// Result<T, E>有两种结果: Ok<T>符合预期, Err<E>不符合预期
fn (a: &str) -> Result<i32, ParseIntError> {
    match a.parse::<i32>() {
        OK(n) => return Ok(n),
        Err(e) => return Err(e),
}}

// 使用?运算符
fn muli(a: &str, b: &str) -> Result<i32, ParseIntError> {
    let mut s = String::new();
    let mut f = File::open("xx.txt")?;  // 结果为Err时, 会直接返回Err
    f.read_to_string(&mut s)?;
    // File::open("xx.txt")?.read_to_string(&mut s)?;  // 链式调用形式
    Ok(s)
}

// 使用unwrap处理Result
fn parse_str(val: &str) -> i32 {
    val.parse::<i32>().unwrap()  // 错误时将返回panic
    // val.parse::<i32>().expect("parse error")  // 自定义错误信息, 同上抛出panic
}

// try!宏, 功能与?类似, 在一些老代码中会使用
fn test(a: &str) -> Result<i32, ParseIntError> { let a = try!(a.parse::<i32>()); ok(a) }
// Result别名
type MyResult<T> = Result<T, ParseIntError>;
```

### 组合器

使用组合器处理Option和Result类型

```rust
// or()和and()
let _ = a1.or(a3);  // or关系, a1为Some或OK返回a1; a1为None或Err, a3为Some或Ok返回a3; 否则返回None或Err
let _ = a2.and(a3);  // and关系, a2和a3都为Some或Ok时, 返回a3

// or_else()和and_then(), 于or()和and()类似, 第二个表达式接受闭包
let _ = b1.or_else(|| Some(3));  // 返回逻辑同or()
let _ = b2.and_then(|| Ok("xx"));  // 返回逻辑同and()

// filter()条件过滤
let (c1, C2): (_, Option<i32>) = (Some(3), None);
let _ = c1.filter(|x: &i32| x % 2 == 0, c2);  // 条件为真返回c1, 否则返回c2

// map()或map_err(), 处理并包装处理结果
let _ = d1.map(|x| format!("{}", x));  // 将map中返回结果用Option和Result重新包装返回
let _ = d1.map_err(|x| x.parse().unwrap());  // 处理Err值

// map_or()和map_or_else()
let _ = e1.map_or("12", |x| format!("{}", x));  // 提供一个默认值
let _ = e1.map_or_else(|| "2", |x| format!("{}", x));  // 使用闭包提供默认值

// ok_or()和ok_or_else(), 将Option类型转为Result类型
let _ = f1.ok_or("err");  // 将f1为Some则转为Ok, 否则将默认"err"转为Err
let _ = f1.ok_or_else(|| "err");  // 接收闭包作为Err参数

// 组合器可进行链式调用

// Option和Result混合使用
fn vec_one(val: Vec<&str>) -> Option<Result<i32, ParseIntError>> {
    val.first().map(|a| { a.parse::<i32>().map(|n| 2 * n) })
}
fn vec_two(val: Vec<&str>) -> Result<Option<i32, ParseIntError>> {
    let opt = val.first().map(|a| { a.parse::<i32>().map(|n| 2 * n) });
    opt.map_or(Ok(None), |r| r.map(Some))
}

// 遍历Result, 过滤失败项
let num: Vec<_> = vals.into_iter().filter_map(|s| s.parse::<i32>().ok()).collect();

// 遍历Result, 失败时终止遍历
let num: Result<Vec<_>, _> = vals.into_iter().map(|s| s.parse::<i32>()).collect();

// 遍历Result, 分开收集合法值和错误
let (num, errs): (Vec<_>, Vec<_>) = vals.into_iter()
                                        .map(|s| s.parse::<i32>())
                                        .partition(Result::is_ok);
let num: Vec<_> = num.into_iter().map(Result::unwrap).collect();  // 提取合法值
let errs: Vec<_> = errs.into_iter().map(Result::unwrap_err).collect();  /// 提取错误
```

### 自定义错误类型

rust自定义错误类型格式：

```rust
use std::{error, fmt};  // 引用标准库

#[derive(Debug, Clone)]  // 自定义错误类型
struct MyError;
impl fmt::Display for MyError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "error information")  // 错误描述
}}
impl error::Error for MyError {  // 实现Error trait
    fn source(&self) -> Option<&(dyn error::Error + 'static)> { None }
}
type Result<i32> = std::result::Result<T, MyError>;  // 包装自定义类型

// 自定义错误使用
fn parse_str(val: Vec<&str>) -> Result<i32> {
    val.first().ok_or(MyError)  // 转换为自定义错误类型
        .and_then(|s| { s.parse::<i32>().map_err(|_| MyError)  // 转换为自定义错误
        .map(|i| 2 * i)
    })
}

// 使用?, 在错误可转换成返回类型的地方, 自动转换返回类型
fn parse_str(val: Vec<&str>) -> Result<i32> {
    let first = val.first().ok_or(MyError)?;  // 自动转换返回类型
    let res = first.parse::<i32>()?;  // 省略map_err
    Ok(2 * res)
}

// 使用Box包装
type Result<T> = std::result::Result<T, Box<dyn error::Error>>;

// 包裹错误
enum MyError { EmptyVec, Parse(ParseIntError), }
```

